#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="19239/158103/Joomla_3.2.3-Stable-Full_Package.tar.gz"
URL="http://joomlacode.org/gf/download/frsrelease/$VERSION"

dl $URL /usr/local/src
